/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra2.pkg2_dennischirinos_lab2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author denni
 */
public class Frame extends javax.swing.JFrame {
    
    int count = 0;
    ArrayList<Ruso> listRusos = new ArrayList();
    ArrayList<Aleman> listAlemanes = new ArrayList();
    ArrayList<Alumno> listAlumnos = new ArrayList();
    ArrayList<Arma> listArmas = new ArrayList();
    ArrayList<Ruso> listMuertos1 = new ArrayList();
    ArrayList<Aleman> listMuertos2 = new ArrayList();
    ArrayList<Alumno> listMuertos3 = new ArrayList();

    /**
     * Creates new form Frame
     */
    public Frame() {
        listArmas.add(new Arma("AK-47", "Ruso", 27));
        listArmas.add(new Arma("Revolver Navant", "Ruso", 13));
        listArmas.add(new Arma("RPG-7", "Ruso", 57));
        
        listArmas.add(new Arma("Ametralladora MG42", "Aleman", 32));
        listArmas.add(new Arma("Pistholas Walter P38", "Aleman", 11));
        listArmas.add(new Arma("MP-40", "Aleman", 25));
        
        listArmas.add(new Arma("Disco Duro", "Alumno", 23));
        listArmas.add(new Arma("Control de wii", "Alumno", 47));
        listArmas.add(new Arma("Laptop", "Alumno", 76));
        
        initComponents();
        CB_JD1_Armas.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Agregar = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        RB_JD1_Ruso = new javax.swing.JRadioButton();
        RB_JD1_Aleman = new javax.swing.JRadioButton();
        RB_JD1_Alumno = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CB_JD1_Armas = new javax.swing.JComboBox<>();
        TF_JD1_Res = new javax.swing.JTextField();
        Pnl_JD1_Ruso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_JD1_ID = new javax.swing.JTextField();
        TF_JD1_Edad = new javax.swing.JTextField();
        TF_JD1_Rango = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Pnl_JD1_Aleman = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TF_JD1_Alias = new javax.swing.JTextField();
        TF_JD1_Casta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Pnl_JD1_Alumno = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TF_JD1_Alias1 = new javax.swing.JTextField();
        TF_JD1_Cuenta = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TF_JD1_Edad2 = new javax.swing.JTextField();
        JD_Modificar = new javax.swing.JDialog();
        Pnl_JD2_Alumno = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TF_JD2_Alias2 = new javax.swing.JTextField();
        TF_JD2_Cuenta = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        TF_JD2_Edad2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RB_JD2_Ruso = new javax.swing.JRadioButton();
        RB_JD2_Aleman = new javax.swing.JRadioButton();
        RB_JD2_Alumno = new javax.swing.JRadioButton();
        Pnl_JD2_Aleman = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TF_JD2_Alias = new javax.swing.JTextField();
        TF_JD2_Casta = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CB_JD2_Armas = new javax.swing.JComboBox<>();
        TF_JD2_Res = new javax.swing.JTextField();
        Pnl_JD2_Ruso = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TF_JD2_ID = new javax.swing.JTextField();
        TF_JD2_Edad = new javax.swing.JTextField();
        TF_JD2_Rango = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        CB_JD2_Soldados = new javax.swing.JComboBox<>();
        JD_Mostrar = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        JD_Batalla = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        RB_JD1_Ruso.setText("Ruso");
        RB_JD1_Ruso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_JD1_RusoActionPerformed(evt);
            }
        });

        RB_JD1_Aleman.setText("Aleman");
        RB_JD1_Aleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_JD1_AlemanActionPerformed(evt);
            }
        });

        RB_JD1_Alumno.setText("Alumno");
        RB_JD1_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_JD1_AlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RB_JD1_Ruso)
                    .addComponent(RB_JD1_Aleman))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RB_JD1_Alumno)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_JD1_Ruso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_JD1_Aleman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_JD1_Alumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Resistencia:");

        jLabel3.setText("Arma:");

        CB_JD1_Armas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_JD1_Res)
                    .addComponent(CB_JD1_Armas, 0, 99, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_JD1_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CB_JD1_Armas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jLabel1.setText("Ruso");

        jLabel4.setText("ID");

        jLabel5.setText("Edad");

        jLabel6.setText("Rango");

        TF_JD1_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD1_EdadActionPerformed(evt);
            }
        });

        jButton1.setText("Reclutar Ruso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_JD1_RusoLayout = new javax.swing.GroupLayout(Pnl_JD1_Ruso);
        Pnl_JD1_Ruso.setLayout(Pnl_JD1_RusoLayout);
        Pnl_JD1_RusoLayout.setHorizontalGroup(
            Pnl_JD1_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD1_RusoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_JD1_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_JD1_RusoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(Pnl_JD1_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD1_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD1_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_JD1_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Rango, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_JD1_RusoLayout.setVerticalGroup(
            Pnl_JD1_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD1_RusoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_JD1_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TF_JD1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_JD1_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TF_JD1_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_JD1_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TF_JD1_Rango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Aleman");

        jLabel8.setText("Alias");

        jLabel9.setText("Casta");

        TF_JD1_Casta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD1_CastaActionPerformed(evt);
            }
        });

        jButton2.setText("Reclutar Aleman");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_JD1_AlemanLayout = new javax.swing.GroupLayout(Pnl_JD1_Aleman);
        Pnl_JD1_Aleman.setLayout(Pnl_JD1_AlemanLayout);
        Pnl_JD1_AlemanLayout.setHorizontalGroup(
            Pnl_JD1_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD1_AlemanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_JD1_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_JD1_AlemanLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD1_AlemanLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Casta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD1_AlemanLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_JD1_AlemanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        Pnl_JD1_AlemanLayout.setVerticalGroup(
            Pnl_JD1_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD1_AlemanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_JD1_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(TF_JD1_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_JD1_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(TF_JD1_Casta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Alumno");

        jLabel11.setText("Apodo");

        jLabel12.setText("Cuenta");

        TF_JD1_Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD1_CuentaActionPerformed(evt);
            }
        });

        jButton3.setText("Reclutar Alumno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Edad");

        TF_JD1_Edad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD1_Edad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_JD1_AlumnoLayout = new javax.swing.GroupLayout(Pnl_JD1_Alumno);
        Pnl_JD1_Alumno.setLayout(Pnl_JD1_AlumnoLayout);
        Pnl_JD1_AlumnoLayout.setHorizontalGroup(
            Pnl_JD1_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_JD1_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Alias1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_JD1_AlumnoLayout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD1_Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_JD1_AlumnoLayout.setVerticalGroup(
            Pnl_JD1_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_JD1_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_JD1_AlumnoLayout.createSequentialGroup()
                        .addGroup(Pnl_JD1_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(TF_JD1_Alias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_JD1_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(TF_JD1_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addComponent(TF_JD1_Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_AgregarLayout = new javax.swing.GroupLayout(JD_Agregar.getContentPane());
        JD_Agregar.getContentPane().setLayout(JD_AgregarLayout);
        JD_AgregarLayout.setHorizontalGroup(
            JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AgregarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_JD1_Ruso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pnl_JD1_Aleman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JD_AgregarLayout.createSequentialGroup()
                        .addComponent(Pnl_JD1_Alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        JD_AgregarLayout.setVerticalGroup(
            JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AgregarLayout.createSequentialGroup()
                .addGroup(JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_AgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pnl_JD1_Ruso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_AgregarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_JD1_Aleman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_JD1_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_AgregarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jLabel14.setText("Alumno");

        jLabel15.setText("Apodo");

        jLabel16.setText("Cuenta");

        TF_JD2_Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD2_CuentaActionPerformed(evt);
            }
        });

        jButton4.setText("Reclutar Alumno");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("Edad");

        TF_JD2_Edad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD2_Edad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_JD2_AlumnoLayout = new javax.swing.GroupLayout(Pnl_JD2_Alumno);
        Pnl_JD2_Alumno.setLayout(Pnl_JD2_AlumnoLayout);
        Pnl_JD2_AlumnoLayout.setHorizontalGroup(
            Pnl_JD2_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_JD2_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Alias2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_JD2_AlumnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_JD2_AlumnoLayout.setVerticalGroup(
            Pnl_JD2_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_JD2_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_JD2_AlumnoLayout.createSequentialGroup()
                        .addGroup(Pnl_JD2_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(TF_JD2_Alias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl_JD2_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(TF_JD2_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addComponent(TF_JD2_Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        RB_JD2_Ruso.setText("Ruso");
        RB_JD2_Ruso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_JD2_RusoActionPerformed(evt);
            }
        });

        RB_JD2_Aleman.setText("Aleman");
        RB_JD2_Aleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_JD2_AlemanActionPerformed(evt);
            }
        });

        RB_JD2_Alumno.setText("Alumno");
        RB_JD2_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_JD2_AlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RB_JD2_Ruso)
                    .addComponent(RB_JD2_Aleman))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RB_JD2_Alumno)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_JD2_Ruso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_JD2_Aleman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_JD2_Alumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setText("Aleman");

        jLabel19.setText("Alias");

        jLabel20.setText("Casta");

        TF_JD2_Casta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD2_CastaActionPerformed(evt);
            }
        });

        jButton5.setText("Reclutar Aleman");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_JD2_AlemanLayout = new javax.swing.GroupLayout(Pnl_JD2_Aleman);
        Pnl_JD2_Aleman.setLayout(Pnl_JD2_AlemanLayout);
        Pnl_JD2_AlemanLayout.setHorizontalGroup(
            Pnl_JD2_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD2_AlemanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_JD2_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_JD2_AlemanLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD2_AlemanLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Casta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD2_AlemanLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_JD2_AlemanLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        Pnl_JD2_AlemanLayout.setVerticalGroup(
            Pnl_JD2_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD2_AlemanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_JD2_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(TF_JD2_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_JD2_AlemanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(TF_JD2_Casta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("Resistencia:");

        jLabel22.setText("Arma:");

        CB_JD2_Armas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_JD2_Res)
                    .addComponent(CB_JD2_Armas, 0, 99, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TF_JD2_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(CB_JD2_Armas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jLabel23.setText("Ruso");

        jLabel24.setText("ID");

        jLabel25.setText("Edad");

        jLabel26.setText("Rango");

        TF_JD2_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_JD2_EdadActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar Ruso");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_JD2_RusoLayout = new javax.swing.GroupLayout(Pnl_JD2_Ruso);
        Pnl_JD2_Ruso.setLayout(Pnl_JD2_RusoLayout);
        Pnl_JD2_RusoLayout.setHorizontalGroup(
            Pnl_JD2_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD2_RusoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_JD2_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_JD2_RusoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(Pnl_JD2_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD2_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_JD2_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_JD2_RusoLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_JD2_Rango, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_JD2_RusoLayout.setVerticalGroup(
            Pnl_JD2_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_JD2_RusoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_JD2_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(TF_JD2_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_JD2_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(TF_JD2_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_JD2_RusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(TF_JD2_Rango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CB_JD2_Soldados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_JD2_Soldados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB_JD2_SoldadosMouseClicked(evt);
            }
        });
        CB_JD2_Soldados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_JD2_SoldadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_ModificarLayout = new javax.swing.GroupLayout(JD_Modificar.getContentPane());
        JD_Modificar.getContentPane().setLayout(JD_ModificarLayout);
        JD_ModificarLayout.setHorizontalGroup(
            JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB_JD2_Soldados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_JD2_Ruso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pnl_JD2_Aleman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addComponent(Pnl_JD2_Alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(32, 32, 32))
        );
        JD_ModificarLayout.setVerticalGroup(
            JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModificarLayout.createSequentialGroup()
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pnl_JD2_Ruso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_ModificarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_JD2_Aleman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_JD2_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_JD2_Soldados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        jButton8.setText("Mostrar Rusos Muertos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Mostrar Alemanes Muertos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Mostrar Alumnos Muertos");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_MostrarLayout = new javax.swing.GroupLayout(JD_Mostrar.getContentPane());
        JD_Mostrar.getContentPane().setLayout(JD_MostrarLayout);
        JD_MostrarLayout.setHorizontalGroup(
            JD_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JD_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_MostrarLayout.setVerticalGroup(
            JD_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_MostrarLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(JD_MostrarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jButton7.setText("Empezar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_BatallaLayout = new javax.swing.GroupLayout(JD_Batalla.getContentPane());
        JD_Batalla.getContentPane().setLayout(JD_BatallaLayout);
        JD_BatallaLayout.setHorizontalGroup(
            JD_BatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BatallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        JD_BatallaLayout.setVerticalGroup(
            JD_BatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BatallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Reclutar Soldado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Modificar Soldado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Mostrar Soldados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Batalla");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Empezar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        JD_Agregar.pack();
        JD_Agregar.setVisible(true);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void TF_JD1_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD1_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD1_EdadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ID = count;
        this.count++;
        int Edad = Integer.parseInt(TF_JD1_Edad.getText());
        int Rango = Integer.parseInt(TF_JD1_Rango.getText());
        int Resistencia = Integer.parseInt(TF_JD1_Res.getText());
        Arma ar = null;
        System.out.println(listArmas.size());
        for (int i = 0; i < listArmas.size(); i++) {
            if (CB_JD1_Armas.getSelectedItem().equals(listArmas.get(i).getTipo())) {
                ar = listArmas.get(i);
            }
        }
        Ruso c = new Ruso(ID, Edad, Rango, Resistencia, ar);
        System.out.println("poder: " + ar.getPoder() + " tipo " + ar.getTipo());
        System.out.println(c.toString());
        listRusos.add(c);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RB_JD1_AlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_JD1_AlemanActionPerformed
        RB_JD1_Alumno.setSelected(false);
        RB_JD1_Ruso.setSelected(false);
        Pnl_JD1_Ruso.setVisible(false);
        Pnl_JD1_Aleman.setVisible(true);
        Pnl_JD1_Alumno.setVisible(false);
        actualizar(2);
    }//GEN-LAST:event_RB_JD1_AlemanActionPerformed

    private void RB_JD1_RusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_JD1_RusoActionPerformed
        RB_JD1_Alumno.setSelected(false);
        RB_JD1_Aleman.setSelected(false);
        Pnl_JD1_Ruso.setVisible(true);
        Pnl_JD1_Aleman.setVisible(false);
        Pnl_JD1_Alumno.setVisible(false);
        actualizar(1);
    }//GEN-LAST:event_RB_JD1_RusoActionPerformed

    private void RB_JD1_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_JD1_AlumnoActionPerformed
        RB_JD1_Ruso.setSelected(false);
        RB_JD1_Aleman.setSelected(false);
        Pnl_JD1_Ruso.setVisible(false);
        Pnl_JD1_Aleman.setVisible(false);
        Pnl_JD1_Alumno.setVisible(true);
        actualizar(3);
    }//GEN-LAST:event_RB_JD1_AlumnoActionPerformed

    private void TF_JD1_CastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD1_CastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD1_CastaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Alias = TF_JD1_Alias.getText();
        String Casta = TF_JD1_Casta.getText();
        int Resistencia = Integer.parseInt(TF_JD1_Res.getText());
        Arma ar = null;
        for (int i = 0; i < listArmas.size(); i++) {
            if (CB_JD1_Armas.getSelectedItem().equals(listArmas.get(i).getTipo())) {
                ar = listArmas.get(i);
            }
        }
        Aleman c = new Aleman(Alias, Casta, Resistencia, ar);
        listAlemanes.add(c);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TF_JD1_CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD1_CuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD1_CuentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Apodo = TF_JD1_Alias1.getText();
        int Edad = Integer.parseInt(TF_JD1_Edad2.getText());
        int Cuenta = Integer.parseInt(TF_JD1_Cuenta.getText());
        int Resistencia = Integer.parseInt(TF_JD1_Res.getText());
        Arma ar = null;
        for (int i = 0; i < listArmas.size(); i++) {
            if (CB_JD1_Armas.getSelectedItem().equals(listArmas.get(i))) {
                ar = listArmas.get(i);
            }
        }
        Alumno c = new Alumno(Apodo, Cuenta, Edad, Resistencia, ar);
        listAlumnos.add(c);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TF_JD1_Edad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD1_Edad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD1_Edad2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JD_Agregar.pack();
        JD_Agregar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TF_JD2_CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD2_CuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD2_CuentaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TF_JD2_Edad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD2_Edad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD2_Edad2ActionPerformed

    private void RB_JD2_RusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_JD2_RusoActionPerformed
        actualizar2(1);
        RB_JD2_Aleman.setSelected(false);
        RB_JD2_Alumno.setSelected(false);
    }//GEN-LAST:event_RB_JD2_RusoActionPerformed

    private void RB_JD2_AlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_JD2_AlemanActionPerformed
        actualizar2(2);
        RB_JD2_Ruso.setSelected(false);
        RB_JD2_Alumno.setSelected(false);
    }//GEN-LAST:event_RB_JD2_AlemanActionPerformed

    private void RB_JD2_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_JD2_AlumnoActionPerformed
        actualizar2(3);
        RB_JD2_Aleman.setSelected(false);
        RB_JD2_Ruso.setSelected(false);
    }//GEN-LAST:event_RB_JD2_AlumnoActionPerformed

    private void TF_JD2_CastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD2_CastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD2_CastaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TF_JD2_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_JD2_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_JD2_EdadActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int ID = count;
        this.count++;
        int Edad = Integer.parseInt(TF_JD2_Edad.getText());
        int Rango = Integer.parseInt(TF_JD2_Rango.getText());
        int Resistencia = Integer.parseInt(TF_JD2_Res.getText());
        Arma ar = null;
        System.out.println(listArmas.size());
        for (int i = 0; i < listArmas.size(); i++) {
            System.out.println("entre for");
            if (CB_JD2_Armas.getSelectedItem().equals(listArmas.get(i).getTipo())) {
                ar = listArmas.get(i);
            }
        }
        Ruso c = new Ruso(ID, Edad, Rango, Resistencia, ar);
        System.out.println("poder: " + ar.getPoder() + " tipo " + ar.getTipo());
        System.out.println(c.toString());
        listRusos.set(CB_JD2_Soldados.getSelectedIndex(), c);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JD_Modificar.pack();
        JD_Modificar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CB_JD2_SoldadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_JD2_SoldadosActionPerformed
        if (RB_JD2_Ruso.isSelected()) {
            Ruso c = listRusos.get(CB_JD2_Soldados.getSelectedIndex());
            TF_JD2_Edad.setText(c.getEdad() + "");
            TF_JD2_ID.setText(c.getID() + "");
            TF_JD2_Rango.setText(c.getRango() + "");
            TF_JD2_Res.setText(c.getResistencia() + "");
        }
        if (RB_JD2_Aleman.isSelected()) {
            Aleman c = listAlemanes.get(CB_JD2_Soldados.getSelectedIndex());
            TF_JD2_Alias.setText(c.getAlias());
            TF_JD2_Casta.setText(c.getCasta());
            TF_JD2_Res.setText(c.getResistencia() + "");
        }
        if (RB_JD2_Alumno.isSelected()) {
            Alumno c = listAlumnos.get(CB_JD2_Soldados.getSelectedIndex());
            TF_JD2_Alias2.setText(c.getApodo());
            TF_JD2_Cuenta.setText(c.getCuenta() + "");
            TF_JD2_Edad2.setText(c.getEdad() + "");
            TF_JD2_Res.setText(c.getResistencia() + "");
        }
    }//GEN-LAST:event_CB_JD2_SoldadosActionPerformed

    private void CB_JD2_SoldadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB_JD2_SoldadosMouseClicked
        if (RB_JD2_Ruso.isSelected()) {
            Ruso c = listRusos.get(CB_JD2_Soldados.getSelectedIndex());
            TF_JD2_Edad.setText(c.getEdad() + "");
            TF_JD2_ID.setText(c.getID() + "");
            TF_JD2_Rango.setText(c.getRango() + "");
            TF_JD2_Res.setText(c.getResistencia() + "");
        }
        if (RB_JD2_Aleman.isSelected()) {
            Aleman c = listAlemanes.get(CB_JD2_Soldados.getSelectedIndex());
            TF_JD2_Alias.setText(c.getAlias());
            TF_JD2_Casta.setText(c.getCasta());
            TF_JD2_Res.setText(c.getResistencia() + "");
        }
        if (RB_JD2_Alumno.isSelected()) {
            Alumno c = listAlumnos.get(CB_JD2_Soldados.getSelectedIndex());
            TF_JD2_Alias2.setText(c.getApodo());
            TF_JD2_Cuenta.setText(c.getCuenta() + "");
            TF_JD2_Edad2.setText(c.getEdad() + "");
            TF_JD2_Res.setText(c.getResistencia() + "");
        }
    }//GEN-LAST:event_CB_JD2_SoldadosMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ArrayList<Ruso> Army1 = listRusos;
        System.out.println(Army1.size());
        ArrayList<Aleman> Army2 = listAlemanes;
        System.out.println(Army2.size());
        ArrayList<Alumno> Army3 = listAlumnos;
        System.out.println(Army3.size());
        Boolean victoria = true;
        System.out.println("Empezo Batalla");
        while (victoria) {
            int mayor;
            int menor;
            if (Army1.size() >= Army2.size()) {
                menor = Army2.size();
                mayor = Army1.size();
            } else {
                menor = Army1.size();
                mayor = Army2.size();
            }
            for (int i = 0; i < menor; i++) {
                Ruso c = Army1.get(i);
                Army2.get(i).setResistencia(Army2.get(i).getResistencia() - c.getArma().getPoder());
            }
            for (int i = menor - 1; i < mayor - 1; i++) {
                Ruso c = Army1.get(i);
                int ATK = Army2.get(Army2.size() - 1).getResistencia() - c.getArma().getPoder();
                Army2.get(Army2.size() - 1).setResistencia(ATK);
            }
            System.out.println("");
            for (int i = 0; i < Army2.size(); i++) {
                Aleman c = Army2.get(i);
                System.out.println(c.getAlias() + " tiene una resistencia de: " + c.getResistencia());
                if (c.getResistencia() <= 0) {
                    System.out.println(c.getAlias() + " ha sido vencido!");
                    listMuertos2.add(c);
                    Army2.remove(i);
                }
            }
            //
            if (Army1.size() >= Army3.size()) {
                menor = Army3.size();
                mayor = Army1.size();
            } else {
                menor = Army1.size();
                mayor = Army3.size();
            }
            try {
                for (int i = 0; i < menor; i++) {
                    Ruso c = Army1.get(i);
                    Army3.get(i).setResistencia(Army3.get(i).getResistencia() - c.getArma().getPoder());
                }
                for (int i = menor - 1; i < mayor - 1; i++) {
                    Ruso c = Army1.get(i);
                    int ATK = Army3.get(Army3.size() - 1).getResistencia() - c.getArma().getPoder();
                    Army3.get(Army3.size() - 1).setResistencia(ATK);
                }
                System.out.println("");
                for (int i = 0; i < Army3.size(); i++) {
                    Alumno c = Army3.get(i);
                    System.out.println(c.getApodo() + " tiene una resistencia de: " + c.getResistencia());
                    if (c.getResistencia() <= 0) {
                        System.out.println(c.getApodo() + " ha sido vencido!");
                        listMuertos3.add(c);
                        Army3.remove(i);
                    }
                }
            } catch (Exception e) {
            }
            System.out.println("mayor: " + mayor);
            System.out.println("menor: " + menor);
            try {
                for (int i = 0; i < menor; i++) {
                    System.out.println(i + ":" + menor);
                    Aleman c = Army2.get(i);
                    Army1.get(i).setResistencia(Army1.get(i).getResistencia() - c.getArma().getPoder());
                }
                //Faltantes
                for (int i = menor - 1; i < mayor - 1; i++) {
                    System.out.println(i + ":" + mayor);
                    Aleman c = Army2.get(i);
                    int ATK = Army1.get(Army1.size() - 1).getResistencia() - c.getArma().getPoder();
                    Army1.get(Army3.size() - 1).setResistencia(ATK);
                }
                //Resultados
                System.out.println("");
                for (int i = 0; i < Army1.size(); i++) {
                    Ruso c = Army1.get(i);
                    System.out.println(c.getID() + " tiene una resistencia de: " + c.getResistencia());
                    if (c.getResistencia() <= 0) {
                        System.out.println(c.getID() + " ha sido vencido!");
                        listMuertos1.add(c);
                        Army1.remove(i);
                    }
                }
            } catch (Exception e) {
            }
            //Mayor o menor
            if (Army2.size() >= Army1.size()) {
                menor = Army1.size();
                mayor = Army2.size();
            } else {
                menor = Army2.size();
                mayor = Army1.size();
            }
            //Batalla

            //
            //Mayor o menor 2.2
            if (Army2.size() >= Army3.size()) {
                menor = Army3.size();
                mayor = Army2.size();
            } else {
                menor = Army2.size();
                mayor = Army3.size();
            }
            try {
                //Batalla 2.2
                for (int i = 0; i < menor; i++) {
                    System.out.println(i + ":" + menor);
                    Aleman c = Army2.get(i);
                    Army3.get(i).setResistencia(Army3.get(i).getResistencia() - c.getArma().getPoder());
                }
                //Faltantes 2.2
                for (int i = menor - 1; i < mayor - 1; i++) {
                    System.out.println(i + ":" + mayor);
                    Aleman c = Army2.get(i);
                    int ATK = Army3.get(Army3.size() - 1).getResistencia() - c.getArma().getPoder();
                    Army3.get(Army3.size() - 1).setResistencia(ATK);
                }
                //Resultados 2.2
                System.out.println("");
                for (int i = 0; i < Army3.size(); i++) {
                    Alumno c = Army3.get(i);
                    System.out.println(c.getApodo() + " tiene una resistencia de: " + c.getResistencia());
                    if (c.getResistencia() <= 0) {
                        System.out.println(c.getApodo() + " ha sido vencido!");
                        listMuertos3.add(c);
                        Army3.remove(i);
                    }
                }
            } catch (Exception e) {
            }

            //
            //Mayor o menor 3.1
            if (Army3.size() >= Army1.size()) {
                menor = Army1.size();
                mayor = Army3.size();
            } else {
                menor = Army3.size();
                mayor = Army1.size();
            }
            try {
                //Batalla 3.1
                for (int i = 0; i < menor; i++) {
                    System.out.println(i + ":" + menor);
                    Alumno c = Army3.get(i);
                    Army1.get(i).setResistencia(Army1.get(i).getResistencia() - c.getArma().getPoder());
                }
                //Faltantes 3.1
                for (int i = menor - 1; i < mayor - 1; i++) {
                    System.out.println(i + ":" + mayor);
                    Alumno c = Army3.get(i);
                    int ATK = Army1.get(Army1.size() - 1).getResistencia() - c.getArma().getPoder();
                    Army1.get(Army1.size() - 1).setResistencia(ATK);
                }
                //Resultados 3.1
                System.out.println("");
                for (int i = 0; i < Army1.size(); i++) {
                    Ruso c = Army1.get(i);
                    System.out.println(c.getID() + " tiene una resistencia de: " + c.getResistencia());
                    if (c.getResistencia() <= 0) {
                        System.out.println(c.getID() + " ha sido vencido!");
                        listMuertos1.add(c);
                        Army1.remove(i);
                    }
                }
            } catch (Exception e) {
            }

            //
            //Mayor o menor 3.2
            if (Army3.size() >= Army2.size()) {
                menor = Army2.size();
                mayor = Army3.size();
            } else {
                menor = Army3.size();
                mayor = Army2.size();
            }
            try {
                for (int i = 0; i < menor; i++) {
                    System.out.println(i + ":" + menor);
                    Alumno c = Army3.get(i);
                    Army2.get(i).setResistencia(Army2.get(i).getResistencia() - c.getArma().getPoder());
                }
                //Faltantes
                for (int i = menor - 1; i < mayor - 1; i++) {
                    System.out.println(i + ":" + mayor);
                    Alumno c = Army3.get(i);
                    int ATK = Army2.get(Army2.size() - 1).getResistencia() - c.getArma().getPoder();
                    Army2.get(Army2.size() - 1).setResistencia(ATK);
                }
                //Resultados
                System.out.println("");
                for (int i = 0; i < Army1.size(); i++) {
                    Aleman c = Army2.get(i);
                    System.out.println(c.getAlias() + " tiene una resistencia de: " + c.getResistencia());
                    if (c.getResistencia() <= 0) {
                        System.out.println(c.getAlias() + " ha sido vencido!");
                        listMuertos2.add(c);
                        Army2.remove(i);
                    }
                }
            } catch (Exception e) {
            }
            //Batalla 3.2

            int armies = 3;
            if (Army1.isEmpty()) {
                armies--;
            }
            if (Army2.isEmpty()) {
                armies--;
            }
            if (Army3.isEmpty()) {
                armies--;
            }
            if (armies <= 1) {
                victoria = false;
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JD_Batalla.pack();
        JD_Batalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Edad");
        model.addColumn("Rango");
        model.addColumn("Resistencia");
        model.addColumn("Arma");
        if (listMuertos1.size() >= 0) {
            Object[] o = new Object[model.getColumnCount()];
            for (int i = 0; i < listMuertos1.size(); i++) {
                o[0] = listMuertos1.get(i).getID();
                o[1] = listMuertos1.get(i).getEdad();
                o[2] = listMuertos1.get(i).getRango();
                o[3] = listMuertos1.get(i).getResistencia();
                o[4] = listMuertos1.get(i).getArma();
                model.addRow(o);
            }
        }
        Tabla.setModel(model);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Alias");
        model.addColumn("Casta");
        model.addColumn("Resistencia");
        model.addColumn("Arma");
        if (listMuertos2.size() >= 0) {
            Object[] o = new Object[model.getColumnCount()];
            for (int i = 0; i < listMuertos2.size(); i++) {
                o[0] = listMuertos2.get(i).getAlias();
                o[1] = listMuertos2.get(i).getCasta();
                o[2] = listMuertos2.get(i).getResistencia();
                o[3] = listMuertos2.get(i).getArma();
                model.addRow(o);
            }
        }
        Tabla.setModel(model);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Apodo");
        model.addColumn("Cuenta");
        model.addColumn("Edad");
        model.addColumn("Resistencia");
        model.addColumn("Arma");
        if (listMuertos3.size() >= 0) {
            Object[] o = new Object[model.getColumnCount()];
            for (int i = 0; i < listMuertos3.size(); i++) {
                o[0] = listMuertos3.get(i).getApodo();
                o[1] = listMuertos3.get(i).getCuenta();
                o[2] = listMuertos3.get(i).getEdad();
                o[3] = listMuertos3.get(i).getResistencia();
                o[4] = listMuertos3.get(i).getArma();
                model.addRow(o);
            }
        }
        Tabla.setModel(model);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JD_Mostrar.pack();
        JD_Mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    
    public void actualizar(int op) {
        CB_JD1_Armas.removeAllItems();
        switch (op) {
            case 1:
                for (int i = 0; i < listArmas.size(); i++) {
                    if (listArmas.get(i).getPais().equals("Ruso")) {
                        CB_JD1_Armas.addItem(listArmas.get(i).toString());
                    }
                }
                break;
            case 2:
                for (int i = 0; i < listArmas.size(); i++) {
                    if (listArmas.get(i).getPais().equals("Aleman")) {
                        CB_JD1_Armas.addItem(listArmas.get(i).toString());
                    }
                }
                break;
            case 3:
                for (int i = 0; i < listArmas.size(); i++) {
                    if (listArmas.get(i).getPais().equals("Alumno")) {
                        CB_JD1_Armas.addItem(listArmas.get(i).toString());
                    }
                }
                break;
        }
    }
    
    public void actualizar2(int op) {
        CB_JD2_Armas.removeAllItems();
        CB_JD2_Soldados.removeAllItems();
        switch (op) {
            case 1:
                for (int i = 0; i < listArmas.size(); i++) {
                    if (listArmas.get(i).getPais().equals("Ruso")) {
                        CB_JD2_Armas.addItem(listArmas.get(i).toString());
                    }
                }
                for (int j = 0; j < listRusos.size(); j++) {
                    CB_JD2_Soldados.addItem(listRusos.get(j).getID() + "");
                }
                break;
            case 2:
                for (int i = 0; i < listArmas.size(); i++) {
                    if (listArmas.get(i).getPais().equals("Aleman")) {
                        CB_JD2_Armas.addItem(listArmas.get(i).toString());
                    }
                }
                for (int j = 0; j < listRusos.size(); j++) {
                    CB_JD2_Soldados.addItem(listAlemanes.get(j).getAlias());
                }
                break;
            case 3:
                for (int i = 0; i < listArmas.size(); i++) {
                    if (listArmas.get(i).getPais().equals("Alumno")) {
                        CB_JD2_Armas.addItem(listArmas.get(i).toString());
                    }
                }
                for (int j = 0; j < listRusos.size(); j++) {
                    CB_JD2_Soldados.addItem(listAlumnos.get(j).getApodo());
                }
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_JD1_Armas;
    private javax.swing.JComboBox<String> CB_JD2_Armas;
    private javax.swing.JComboBox<String> CB_JD2_Soldados;
    private javax.swing.JDialog JD_Agregar;
    private javax.swing.JDialog JD_Batalla;
    private javax.swing.JDialog JD_Modificar;
    private javax.swing.JDialog JD_Mostrar;
    private javax.swing.JPanel Pnl_JD1_Aleman;
    private javax.swing.JPanel Pnl_JD1_Alumno;
    private javax.swing.JPanel Pnl_JD1_Ruso;
    private javax.swing.JPanel Pnl_JD2_Aleman;
    private javax.swing.JPanel Pnl_JD2_Alumno;
    private javax.swing.JPanel Pnl_JD2_Ruso;
    private javax.swing.JRadioButton RB_JD1_Aleman;
    private javax.swing.JRadioButton RB_JD1_Alumno;
    private javax.swing.JRadioButton RB_JD1_Ruso;
    private javax.swing.JRadioButton RB_JD2_Aleman;
    private javax.swing.JRadioButton RB_JD2_Alumno;
    private javax.swing.JRadioButton RB_JD2_Ruso;
    private javax.swing.JTextField TF_JD1_Alias;
    private javax.swing.JTextField TF_JD1_Alias1;
    private javax.swing.JTextField TF_JD1_Casta;
    private javax.swing.JTextField TF_JD1_Cuenta;
    private javax.swing.JTextField TF_JD1_Edad;
    private javax.swing.JTextField TF_JD1_Edad2;
    private javax.swing.JTextField TF_JD1_ID;
    private javax.swing.JTextField TF_JD1_Rango;
    private javax.swing.JTextField TF_JD1_Res;
    private javax.swing.JTextField TF_JD2_Alias;
    private javax.swing.JTextField TF_JD2_Alias2;
    private javax.swing.JTextField TF_JD2_Casta;
    private javax.swing.JTextField TF_JD2_Cuenta;
    private javax.swing.JTextField TF_JD2_Edad;
    private javax.swing.JTextField TF_JD2_Edad2;
    private javax.swing.JTextField TF_JD2_ID;
    private javax.swing.JTextField TF_JD2_Rango;
    private javax.swing.JTextField TF_JD2_Res;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
